console.log('Helllllooo!')
console.log('It is amazing, when you can type code and see resoult!!!')
console.log('Helllllooo!')
console.log('It is amazing, when you can type code and see resoult!!!')
console.log('Helllllooo!')
console.log('It is amazing, when you can type code and see resoult!!!')
console.log('Helllllooo!')
console.log('It is amazing, when you can type code and see resoult!!!')
console.log('Helllllooo!')
console.log('It is amazing, when you can type code and see resoult!!!')